### ISSUE TITLE
How to warp?

### ISSUE THREAD

**Issue by tuvovan** [hmorimitsu/sift-flow-gpu#2]
Hi,

Given the calculated flow, how to warp an image A to image B? Thanks!

**Comment by hmorimitsu** [comment]
Hi,

I haven't written code for that operation, but you can look at other optical flow repos that offer these functions.

For backward warping, you can look at the `WarpingLayer` at https://github.com/visinf/irr/blob/master/models/pwc_modules.py.

For forward warping, you could adapt the function `forward_interpolate` from https://github.com/princeton-vl/RAFT/blob/master/core/utils/utils.py to work with images or check the soft-splatting operation at https://github.com/sniklaus/softmax-splatting.

Best,

**Comment by tuvovan** [comment]
I was just looking for a warp function that warp image A to image B with the given motion vectors, no need gradient calculation.
Thank you for the resource!
